POST http://localhost:3001/customers
Content-Type: application/json

{
    "companyName": "Beauty",
    "contactName": "Mirela Donici",
    "contactEmail": "mirela@gmail.com",
    "industry": "e-commerce",
    "projectType":"web_platform",
    "status": "scheduled",
    "deadline": "2026-12-25T16:03:21.482Z",
    "teamMembers": [9]
}