POST http://localhost:3001/customers
Content-Type: application/json

{
    "companyName": "Iasi_Transport",
    "contactName": "Catalin Ceban",
    "contactEmail": "catalin@gmail.com",
    "industry": "transport and logistics",
    "projectType":"crm",
    "status": "scheduled",
    "deadline": "2026-10-03T16:03:21.482Z"
}