POST http://localhost:3001/team-members
Content-Type: application/json
{
    "name": "Adriana",
    "contactNumber": "0735562145",
    "contactEmail":"adriana@gmail.com",
    "role":"admin",
    "password":"Admin26!"
    
    
}