POST http://localhost:3001/team-members
Content-Type: application/json

{
    "name": "Ion Mardari",
    "contactNumber": "0727377727",
    "contactEmail":"ion@gmail.com",
    "customers":["Solo"]
    
}