PATCH http://localhost:3001/team-members/23
Content-Type: application/json

{
    "name": "Ion Mardari",
    "contactNumber": "0735355559",
    "contactEmail": "ion@gmail.com",
    "customers": ["Adrielle"]
}