POST http://localhost:3001/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWlyZWxAZ21haWwuY29tIiwiaWF0IjoxNzc2OTQ5OTc3LCJleHAiOjE3NzY5NTM1NzcsImF1ZCI6ImxvY2FsaG9zdDozMDAxIiwiaXNzIjoibG9jYWxob3N0OjMwMDEifQ.NAvNDLZhap2_cny_frB1s69syy1DEuBINAPY5awVR1I

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTc3Njk0OTk3NywiZXhwIjoxNzc3MDM2Mzc3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.o_45jmxNPw5KUWEQR3N_FKqjlaIEZqfMKa9BhdVO-ZE"
}